name: Build binary

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json -v

      - name: Install dependencies
        run:  arduino-cli lib install ringbuffer pubsubclient doubleresetdetect arduinojson dallastemperature onewire WebSockets

      - name: Update version
        run: echo "static const char *heishamon_version = \"Alpha-${GITHUB_SHA::6}\"" > HeishaMon\version.h && cat HeishaMon\version.h
        shell: bash

      - name: Compile Sketch
        run: cd HeishaMon && arduino-cli compile --fqbn=esp8266:esp8266:d1_mini:xtal=160,vt=flash,ssl=all,eesz=4M2M,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=921600 --vid-pid=1A86_7523 --warnings=none --verbose HeishaMon.ino

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: HeishaMon.ino.bin
          path: C:\\Users\\runneradmin\\AppData\\Local\\Temp\\arduino-sketch-*\\*.ino.bin

